# Generated by Django 4.2.3 on 2023-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='has_rider',
            field=models.BooleanField(default=False),
        ),
    ]
